### ISSUE TITLE
MWG Meeting 03/05/2023

### ISSUE THREAD

**Issue by NicoleKessler** [openedx/wg-marketing#2]
Meeting link  https://meet.jit.si/open-edx-marketing-group
Meeting every two weeks at
Beriln, CEST (UTC +2) 4.00 pm
Boston USA 10.00 am
Search your time zone here: https://www.timeanddate.com/

### Meeting Agenda

**- Hand-over of responsibility of meeting notes (Juan)**

**-How-To Video Release**
Material is ready for publishing

**-Next Open edX Meetup featuring ASU and XIM University:**
link to register: [Local & International University Use Cases of the Open edX Platform](https://may23-meetup.eventbrite.com/)

**-OKR Strategy Review**
OKR Strategy: [OKR´S MWG](https://docs.google.com/spreadsheets/d/10Ju_m1DgERpvfYaFrW7bu5XMU402UqVseCr7IRKBtzw/edit#gid=0)
Please enter 1-2 items you would like to prioritize for 2023, to which you can actively contribute your time.

**-Updated Confluence Page**
linked on website: [Marketing Working Group](https://openedx.atlassian.net/wiki/spaces/COMM/pages/3374972965/Marketing+Working+Group)

**-GH Projects Review**
To complete migration, enter your details here: [GH Project Migration - Marketing WG](https://docs.google.com/spreadsheets/d/1i79j9425vvtNd1XyDqnxyeZU_0ucjvcKFkJnZzgcjCY/edit#gid=0)
Link to board: [Open edX Marketing Working Group • openedx](https://github.com/orgs/openedx/projects/49/views/1)

**- Introduction by Natalia into the project management tool:** https://app.glassfrog.com/organizations/25233/orgnav/roles/13450116 

**-Sandbox**
legal restrictions on compliance and security side - rotation is not an option

**- Exchange of impressions and opinions for using GitHub projects**

**- Brainstorming session** 
Document: https://docs.google.com/document/d/1tKae6W9G0l0h1mqWfXhRjGRhiT74hokQHLfXEMf4HCQ/edit#
OKR Strategy: https://docs.google.com/spreadsheets/d/10Ju_m1DgERpvfYaFrW7bu5XMU402UqVseCr7IRKBtzw/edit#gid=0

**Comment by TanahaRG** [comment]
Thank you very much for the agenda, Nicole. I have one correction 
- - Introduction by Natalia into the project management tool: https://app.glassfrog.com/organizations/25233/orgnav/roles/13450116

It's not a project management tool, I agree we should use gitHub. I suggest to use Holacracy. This is a method of decentralized management and organizational governance to distribute authority and decision-making through self-organizing teams rather than being vested in a management hierarchy. 
I believe it will be a great fit to the open community like Open edX. 

And glassfrog is just a tool that makes holacracy visible.
